#ifndef _CNWSMODULE_H_
#define _CNWSMODULE_H_
#include "nwndef.h"
#include "CExoString.h"
#include "CResRef.h"
#include "CExoLocString.h"
#include "CExoArrayList.h"
#include "CGameObject.h"
#include "CExoLinkedList.h"
#include "CNWSPlayerTURD.h"
#include "CResIFO.h"
#include "CNWSScriptVarTable.h"

class CNWSModule
{
public:
    int AIUpdate();
    void AddObjectToLimbo(unsigned long);
    int AddObjectToLookupTable(CExoString, unsigned long);
    int AddTURDsToWorld();
    void AddToTURDList(CNWSPlayerTURD *);
    int AddWorldJournalEntryStrref(unsigned long, unsigned long, unsigned long, unsigned long);
    void AddWorldJournalEntry(int, CExoString, CExoString, unsigned long, unsigned long);
    CNWSModule * AsNWSModule();
    void CleanUpLimboList();
    int ClearAreaVisitedFlags();
    int ComputeInterAreaPath(CPathfindInformation *);
    int DeleteWorldJournalAllEntries();
    void DeleteWorldJournalEntryStrref(unsigned long);
    void DeleteWorldJournalEntry(int);
    void DoUpdate();
    void EventHandler(unsigned long, unsigned long, void *, unsigned long, unsigned long);
    unsigned long FindObjectByTagOrdinal(CExoString const &, unsigned long);
    unsigned long FindObjectByTagTypeOrdinal(CExoString const &, int, unsigned long);
    int FindTagPositionInTable(char *);
    int GenerateInterAreaDFSSuccessors(int, CPathfindInformation *, unsigned long **);
    int GetAreaByName(CExoString &);
    CNWSArea * GetAreaByTag(CExoString &);
    int GetAreaList();
    CNWSArea * GetArea(CResRef);
    CNWSArea * GetArea(unsigned long);
    int GetCustomScriptEventId();
    int GetDawnHour();
    int GetDuskHour();
    int GetEnableScriptDebugger();
    unsigned char * GetFullCipher(CExoString);
    int GetInvisibleCreaturesList();
    int GetIsDigitalDistributionDemo();
    int GetIsNWMFile();
    int GetIsSaveGame();
    int GetLastEnter();
    int GetLastExit();
    int GetLastItemAcquiredBy();
    int GetLastItemAcquiredFrom();
    int GetLastItemAcquiredStackSize();
    int GetLastItemAcquired();
    int GetLastItemActivatedArea();
    int GetLastItemActivatedPosition();
    int GetLastItemActivatedTarget();
    int GetLastItemActivated();
    int GetLastItemActivator();
    int GetLastItemLoser();
    int GetLastItemLostStackSize();
    int GetLastItemLost();
    int GetLastPCCancelCutscene();
    int GetLastPCLevellingUp();
    int GetLastPlayerChatMessageType();
    CExoString GetLastPlayerChatMessage();
    int GetLastPlayerChatObject();
    int GetLastPlayerDied();
    int GetLastPlayerDying();
    int GetLastRespawnButtonPresser();
    int GetLastRestEventType();
    int GetLastRested();
    int GetLimboArray();
    int GetMaxHenchmen();
    int GetMinutesPerHour();
    CExoLocString GetModuleDescription();
    int GetModuleEntryInfo();
    CExoLocString GetModuleName();
    CExoString GetNWMResName();
    int GetPCItemLastEquippedBy();
    int GetPCItemLastEquipped();
    int GetPCItemLastUnequippedBy();
    int GetPCItemLastUnequipped();
    unsigned long GetPlayerIndexInPlayerList(CNWSPlayer *);
    int GetPlayerPathfindRule();
    CNWSPlayerTURD * GetPlayerTURDFromList(CNWSPlayer *);
    unsigned long GetPrimaryPlayerIndex();
    int GetScriptName(int);
    CNWSScriptVarTable * GetScriptVarTable();
    int GetStartMovie();
    CExoString GetTag();
    int GetTimeOfDayState();
    void GetTime(unsigned long *, unsigned long *, unsigned long *, unsigned long *, unsigned char *, unsigned long *);
    unsigned long GetWaypoint(CExoString const &);
    unsigned long GetWorldJournalIndexUnique();
    int GetXPScale();
    int InterAreaDFS(int, int, CPathfindInformation *);
    int IsObjectInLimbo(unsigned long);
    unsigned char IsOfficialCampaign();
    int LoadLimboCreatures(CResGFF *, CResStruct *, int);
    unsigned long LoadModuleFinish();
    unsigned long LoadModuleInProgress(int, int);
    unsigned long LoadModuleStart(CExoString, int);
    void LoadTURDList(CResGFF *, CResStruct *);
    void PackModuleIntoMessage(unsigned long);
    void PackPlayerCharacterListIntoMessage(CNWSPlayer *, CExoArrayList<NWPlayerCharacterList_st *> &);
    unsigned long PlotInterAreaPath(CPathfindInformation *, unsigned long);
    unsigned long PlotPathInArea(CPathfindInformation *, unsigned long);
    unsigned long PlotPath(CPathfindInformation *, unsigned long);
    void PostProcess();
    void RemoveFromTURDList(CNWSPlayer *);
    void RemoveObjectFromLimbo(unsigned long);
    int RemoveObjectFromLookupTable(CExoString, unsigned long);
    void SaveLimboCreatures(CResGFF *, CResStruct *);
    int SaveModuleFAC(CERFFile *);
    int SaveModuleFinish(CExoString &, CExoString &);
    int SaveModuleIFOFinish(CResGFF *, CResStruct *, CERFFile *, CExoString &, CExoArrayList<unsigned long> &);
    int SaveModuleIFOStart(CResGFF *, CResStruct *);
    int SaveModuleInProgress();
    void SaveModuleStart(CExoString &, CExoString &);
    int SavePlayers(CResGFF *, CResStruct *, CExoString &, CExoArrayList<unsigned long> &);
    int SaveStatic(CERFFile *, CExoString, unsigned short, int);
    int SaveTURDList(CResGFF *, CResStruct *);
    int SetCustomScriptEventId(int);
    int SetEnableScriptDebugger(unsigned char);
    void SetIntraAreaGoal(CPathfindInformation *);
    int SetIsNWMFile(int);
    int SetIsSaveGame(int);
    int SetLastEnter(unsigned long);
    int SetLastExit(unsigned long);
    int SetLastItemAcquiredBy(unsigned long);
    int SetLastItemAcquiredFrom(unsigned long);
    int SetLastItemAcquiredStackSize(int);
    int SetLastItemAcquired(unsigned long);
    int SetLastItemActivatedArea(unsigned long);
    int SetLastItemActivatedPosition(Vector const &);
    int SetLastItemActivatedTarget(unsigned long);
    int SetLastItemActivated(unsigned long);
    int SetLastItemActivator(unsigned long);
    int SetLastItemLoser(unsigned long);
    int SetLastItemLostStackSize(int);
    int SetLastItemLost(unsigned long);
    int SetLastPCCancelCutscene(unsigned long);
    int SetLastPCLevellingUp(unsigned long);
    int SetLastPlayerChatMessageType(unsigned char);
    int SetLastPlayerChatMessage(CExoString const &);
    int SetLastPlayerChatObject(unsigned long);
    int SetLastPlayerDied(unsigned long);
    int SetLastPlayerDying(unsigned long);
    int SetLastRespawnButtonPresser(unsigned long);
    int SetLastRestEventType(unsigned char);
    int SetLastRested(unsigned long);
    int SetMaxHenchmen(int);
    int SetNWMResName(CExoString &);
    int SetPCItemLastEquippedBy(unsigned long);
    int SetPCItemLastEquipped(unsigned long);
    int SetPCItemLastUnequippedBy(unsigned long);
    int SetPCItemLastUnequipped(unsigned long);
    int SetPlayerPathfindRule(unsigned char);
    void SetScriptName(int, CExoString);
    int SetXPScale(unsigned char);
    void TimeStopSanityCheck();
    int UnloadModule();
    void UpdateTime(unsigned long, unsigned long, unsigned long);
    ~CNWSModule();
    CNWSModule(CExoString, int, int);

    // /* 0x10/16 */ unsigned long ModuleExpansionList;
    // /* 0x14/20 */ unsigned long field_14;
    // /* 0x18/24 */ unsigned long AreasResrefList;


    /* 0x00 */    CResIFO IFO;
    /* 0x1C */    CGameObject GameObject;
    /* 0x2C/44 */ unsigned long field_2C;
    /* 0x30/48 */ unsigned long field_30;
    /* 0x34/52 */ unsigned long field_34;
    /* 0x38/56 */ CExoArrayList<nwobjid> AreaIdList;
    /* 0x44/68 */ unsigned long field_44;
    /* 0x48/72 */ unsigned long field_48;
    /* (mtype:CExoLinkedList<CNWSPlayerTURD>) */
    /* 0x4C/76 */ CExoLinkedList<CNWSPlayerTURD> TURDList;
    /* 0x54/88 */ CExoLocString Description;
    /* 0x58/88 */ CExoString m_sCustomTLK;
    uint32_t field_60;
    uint32_t field_64;
    CExoString CurrentGame;
    /* 0x80/128 */ char rsvd2[12];
    uint32_t IsDemo;
    /* 0x80/128 */ unsigned long field_80;
    /* 0x84/132 */ CExoLocString Name;
    /* (mtype:CExoArrayList<CExoString>) */
    /* 0x8C/140 */ CExoArrayList<CExoString> HakList;
    CResRef SomeResref;
    CNWSScriptVarTable VarTable;
    /* 0xB8/184 */ char rsvd3[8];
    /* 0xB8/184 */ CExoString Scripts[18];
    uint32_t field_148;
    uint32_t field_14C;
    uint32_t field_150;
    uint32_t field_154;
    uint32_t field_158;
    CExoArrayList<void*> LookupTable;
    uint32_t field_168;
    uint32_t LastEntered;
    uint32_t LastExited;
    uint32_t LastItemAcquired;
    uint32_t LastItemAcquiredFrom;
    uint32_t LastItemAcquiredBy;
    uint32_t LastItemLost;
    uint32_t LastItemLoser;
    uint32_t LastItemAcquiredStackSize;
    uint32_t LastItemLostStackSize;
    uint32_t field_190;
    uint32_t field_194;
    uint32_t field_198;
    uint32_t field_19C;
    uint32_t LastRested;
    uint32_t LastRestedType;
    uint32_t field_1A8;
    uint32_t LastPlayerDied;
    uint32_t LastPlayerDying;
    uint32_t LastItemActivated;
    uint32_t LastItemActivatedActivator;
    uint32_t LastItemActivatedArea;
    uint32_t LastItemActivatedTarget;
    uint32_t DateYear;
    uint32_t DateMonth;
    uint32_t DateDay;
    uint32_t TimeHour;
    uint32_t field_1D4;
    uint8_t MinutesPerHour;
    uint8_t DawnHour;
    uint8_t DuskHour;
    uint8_t StartMonth;
    uint8_t StartDay;
    uint8_t StartHour;
    uint8_t XPScale;
    uint8_t field_1DF;
    uint32_t StaryYear;
    uint32_t field_1E4;
    uint32_t field_1E8;
    uint32_t field_1EC;
    uint32_t field_1F0;
    uint8_t TimeOfDayState;
    uint8_t field_1F5;
    uint8_t field_1F6;
    uint8_t field_1F7;
    uint32_t field_1F8;
    uint32_t field_1FC;
    uint32_t field_200;
    CExoArrayList<void*> WorldJournalEntries;
    uint8_t field_210;
    uint32_t mod_max_henchmen;
    CExoArrayList<uint32_t> LimboObjects;
    uint32_t SaveGameERF;
    uint32_t field_228;
    uint32_t field_22C;
    uint32_t field_230;
    CExoString Tag;
    uint32_t IsOfficialCampaign_;
    CExoString NWMResName;
    uint32_t TableCount;
    uint8_t PCPathFindRule;
    uint8_t EnableScriptDebugger;
    uint8_t field_24E;
    uint8_t field_24F;
    uint32_t LastPCChatObject;
    CExoString LastPCChatMessage;
    uint32_t LastPCChatType;
};
#endif
